import keyMirror from 'keymirror';

export default keyMirror({

  SITE_FETCH_SUCCESS: null,
  SITE_FETCH_FAIL: null,

  PAGE_INDEX_RESET: null,
  PAGE_INDEX_FETCH_SUCCESS: null,
  PAGE_INDEX_FETCH_FAIL: null,

  PAGE_FETCH_SUCCESS: null,
  PAGE_FETCH_FAIL: null,

  FORM_EDUCATIONS_INDEX_FETCH_SUCCESS: null,
  FORM_EDUCATIONS_INDEX_FETCH_FAIL: null,

  EDUCATIONS_INDEX_FETCH_SUCCESS: null,
  EDUCATIONS_INDEX_FETCH_FAIL: null,
  EDUCATIONS_INDEX_LOADING: null,

  EDUCATIONS_FILTER_SET: null,

  EDUCATION_CURRENT_FETCH_SUCCESS: null,
  EDUCATION_CURRENT_FETCH_FAIL: null,

  NEWS_INDEX_FETCH_SUCCESS: null,
  NEWS_INDEX_FETCH_FAIL: null,

  ARTICLE_INDEX_FETCH_SUCCESS: null,
  ARTICLE_INDEX_FETCH_FAIL: null,

  ARTICLE_BY_SLUG_FETCH_SUCCESS: null,
  ARTICLE_BY_SLUG_FETCH_FAIL: null,

  ARTICLE_BY_TYPE_FETCH_SUCCESS: null,
  ARTICLE_BY_TYPE_FETCH_FAIL: null,

  ARTICLE_BY_ID_FETCH_SUCCESS: null,
  ARTICLE_BY_ID_FETCH_FAIL: null,

  SEARCH_FILTER_SET: null,
  SEARCH_FILTERS_RESET: null,

  MENU_INDEX_FETCH_SUCCESS: null,
  MENU_INDEX_FETCH_FAIL: null,

  MENU_FETCH_SUCCESS: null,
  MENU_FETCH_FAIL: null,

  LOCATIONS_INDEX_FETCH_SUCCESS: null,
  LOCATIONS_INDEX_FETCH_FAIL: null,

  ESTABLISHMENT_INDEX_FETCH_SUCCESS: null,
  ESTABLISHMENT_INDEX_FETCH_FAIL: null,

  ESTABLISHMENT_CURRENT_SET_SUCCESS: null,

  OPTIONS_FETCH_SUCCESS: null,
  OPTIONS_FETCH_FAIL: null,

  FORM_INPUT_SET: null,
});
